### ISSUE TITLE
Uncaught Error: Cannot decorate a destroyed marker

### ISSUE THREAD

**Issue by michalchovanak** [jpohjolainen/atom-highlight-nbsp#5]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.4
**Thrown From**: [highlight-nbsp](https://github.com/jpohjolainen/atom-highlight-nbsp) package 0.1.1

### Stack Trace

Uncaught Error: Cannot decorate a destroyed marker

```
At /Applications/Atom.app/Contents/Resources/app/src/decoration-manager.js:204

Error: Cannot decorate a destroyed marker
    at DecorationManager.module.exports.DecorationManager.decorateMarker (/Applications/Atom.app/Contents/Resources/app/src/decoration-manager.js:194:23)
    at TextEditor.module.exports.TextEditor.decorateMarker (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1737:43)
    at /packages/highlight-nbsp/lib/highlight-nbsp.coffee:15:36
    at ForwardsSingleLine.iterate (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/match-iterator.js:94:17)
    at TextBuffer.module.exports.TextBuffer.scanInRange (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:982:29)
    at TextBuffer.module.exports.TextBuffer.scan (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:935:25)
    at TextEditor.module.exports.TextEditor.scan (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2685:32)
    at /packages/highlight-nbsp/lib/highlight-nbsp.coffee:13:16
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1442:31
```

### Commands

```
     -0:45.7.0 autocomplete-plus:confirm (input.hidden-input)
     -0:45.7.0 snippets:expand (atom-text-editor.editor.is-focused)
  3x -0:44.7.0 core:move-right (input.hidden-input)
     -0:34.9.0 core:backspace (input.hidden-input)
     -0:34.5.0 core:move-right (input.hidden-input)
     -0:32.7.0 autocomplete-plus:confirm (input.hidden-input)
     -0:32.7.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -0:29.8.0 autocomplete-plus:confirm (input.hidden-input)
     -0:28.5.0 core:save (input.hidden-input)
     -0:12.4.0 core:copy (input.hidden-input)
     -0:09.2.0 core:paste (input.hidden-input)
     -0:07.4.0 core:move-right (input.hidden-input)
     -0:06.3.0 autocomplete-plus:confirm (input.hidden-input)
     -0:06.3.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -0:02.9.0 autocomplete-plus:confirm (input.hidden-input)
     -0:01.7.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-autocomplete-php 0.22.2 
atom-beautify 0.29.23 
atom-live-server 2.1.2 
atom-minify 0.8.0 
atom-zurb-foundation 2.0.0 
busy-signal 1.3.0 
emmet 2.4.3 
git-plus 7.6.0 
highlight-bad-chars 1.0.5 
highlight-nbsp 0.1.1 
intentions 1.1.2 
language-babel 2.61.0 
linter 2.1.4 
linter-bootlint 1.0.4 
linter-csslint 1.3.4 
linter-htmlhint 1.3.3 
linter-php 1.3.2 
linter-ui-default 1.2.3 
php-cs-fixer 4.1.0 
pigments 0.39.1 
w3c-validation 0.4.0 
wordpress-api 1.2.2 
```

**Comment by mrlem** [comment]
also happens on ubuntu 17.04 / atom 1.22.1

**Comment by tarnagas** [comment]
Same issue.
Atom ``1.23.0``  Ubuntu ``17.04``
